### PR TITLE
Dynobench tdbastar

### PR DESCRIPTION
**Pull request by akmaralAW**

### CODE REVIEW

**Comment by akmaralAW** [comment]
current tdbA* implementation has been tested, and works for all examples, except alcove_unicycle_sphere with > 100 motion primitives. It will be addressed in March.

**Comment by quimortiz** [comment]
why did you comment all the line where I check that the yaw part of the state is between -pi and pi?

**Comment by akmaralAW** [comment]
Regarding the commenting lines for the yaw state checking. It was needed for the reverse search. Initially I was setting the start state to inf., however just today realized that I just had to set to inf ONLY the position. Fixed now, thanks for pointing it out!

**Comment by quimortiz** [comment]
tests are failing in your branch. Can you check why? It seems that robot yaml files are missing. A possible reason is that at some point I moved the models directory and then moved it back to the original localtion. Maybe git then is confused when merging. Anyway,  I guess you should get the yaml file in your computer, or in a previous commit of your branch. 
[z.txt](https://github.com/quimortiz/dynobench/files/14333310/z.txt)

**Comment by quimortiz** [comment]
i compile and run the tests with: 
`cmake  -S . -B build_tmp -DCMAKE_PREFIX_PATH="/opt/openrobots/;/home/quim/local/" -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .. -DBUILD_ALL=1
`
and then 

`cmake --build build_tmp -j4`

inside build_tmp, 

make test

Or, inside the  build_tmp/test

`
./test_dynobench --log_sink=z.txt
`

**Comment by akmaralAW** [comment]
Now it should work, the problems was due to robot names - here it used the old our format, now it is updated, dynobench_test should work.

**Comment by quimortiz** [comment]
merged, thanks! can you quickly test your code with the main branch?

**Comment by akmaralAW** [comment]
main branch of dbcbs ? in order to run the benchmark?

**Comment by quimortiz** [comment]
i don't know. so you had some code using [dynobench-tdbastar](https://github.com/quimortiz/dynobench/tree/dynobench-tdbastar) -- now this has been merged into main. So that code should work now with the main branch.

**Pull request merged**
